profiles: development
spring:
  datasource:
    url: jdbc:h2:file:./data/devdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
    ddl-auto: update