spring:
  application:
    name: app
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
output:
  ansi:
  enabled: always    # цветной вывод логотипа
logging:
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss"
