spring:
  application:
    name: app
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    ddl-auto: update
    show-sql: true
    hibernate:
      format_sql: true
  h2:
    console:
      enabled: true
output:
  ansi:
  enabled: always    # цветной вывод логотипа
logging:
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss"
